### ISSUE TITLE
May 10 (Mother's Day) Sunday

### ISSUE THREAD

**Issue by WuLan-sudo** [lwg342/ToDo#6]
Do not forget a call please
- [x] **8:30 - 9:30** Cheese Listening and review
- [x] **10:30-12:00** Haircut
- [x] **Afternoon**: paper revising > 2.5h
- [x] **8:00-9:00pm** C++ Meeting
- [x] **9:00-10:00pm** Exercising
- [x] **30min** Brainstorming for video assignment
_Sleep early and have a nice day~_

**Comment by lwg342** [comment]
谢谢提醒啦 你真是个好孩子～

**Comment by lwg342** [comment]
恭喜你完成今天的所有任务～11号也要加油
