### ISSUE TITLE
May 11 Monday

### ISSUE THREAD

**Issue by WuLan-sudo** [lwg342/ToDo#8]
To do list:
Remember to submit EIE3080 before 6pm/ a call after lunch/ a call 4:00pm 
- [x] **8:30** Wake up - breakfast arrives at 8:20
- [x] **9:00 - 10:00** Cheese listening
- [x] **10:00 - 12:00** Paper Revising
- [x] **2:00 - 3:00** C++ Monitor UI design
- [x] **3:00 - 3:40** Exercise Round1
- [ ] **4:00-6:00** Paper Revising
- [x] **7:30 - 8:30** C++ UI improvement
- [x] **8:30 - 9:00** driving test exercise
- [x] **9:00 - 10:00** C++ Project Meeting
- [x] 10:00 - 11:00 Collect Materials for GEB Video Assignment
_Adjust sleeping time~_

**Comment by lwg342** [comment]
Cheese listening 是什么意思呀

**Comment by WuLan-sudo** [comment]
是芝士英语听力～一个公众号

**Comment by lwg342** [comment]
> 是芝士英语听力～一个公众号

加油哦～这个公众号推荐吗

**Comment by WuLan-sudo** [comment]
哈哈虽然芝士英语不错，但是你的听力真的很好,没必要花钱练习
我是每天看无字幕电影学一些口语表达

**Comment by lwg342** [comment]
有好看的电影告诉我～今天辛苦啦 做了这么多事情

**Comment by WuLan-sudo** [comment]
还是有一项没完成sad
